### ISSUE TITLE
Numbers are not replaced with flag names for custom token asm strings

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rizin#3712]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | Hexagon
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.6.0 @ linux-x86-64 commit: 3904d3e347d555fe2f2677a5880f0c588b3463eb

### Expected behavior

Numbers are replace in the asm string with flag names.

Like this:

![hexagon-asm-syntax-general](https://github.com/rizinorg/rizin/assets/45763064/09b171c9-8026-4ea9-9a34-1d7f9623ce64)

### Actual behavior

They are not.

![hexagon-asm-syntax-regex](https://github.com/rizinorg/rizin/assets/45763064/dd90874e-070c-4d3d-be52-2a36464f86ee)

### Steps to reproduce the behavior

Prevent parsing of tokens by commenting out the lines:

https://github.com/rizinorg/rizin/blob/c0b02cf54605eae4b11ec7e159a9e50043e6efa7/librz/asm/arch/hexagon/hexagon_arch.c#L890-L891

and 

https://github.com/rizinorg/rizin/blob/c0b02cf54605eae4b11ec7e159a9e50043e6efa7/librz/asm/arch/hexagon/hexagon_arch.c#L896-L897

Open `test/bins/elf/analysis/hexagon-hello-loop` asm see missing flag replacement.

### Additional Logs, screenshots, source code,  configuration dump, ...

...

**Comment by XVilka** [comment]
@Rot127 wasn't this fixed with the switch to PCRE2?

**Comment by Rot127** [comment]
Just checked it. It's still a problem unfortunately. It replaces always in the top most instruction. I'll check it later this day.
